//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolAutoGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_MASTERS
    {
        public decimal MTM_ID { get; set; }
        public Nullable<decimal> MT_DOMAIN_ID { get; set; }
        public string MT_NAME { get; set; }
        public string MT_REF_TYPE { get; set; }
        public string MT_REF_NO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string AUTH_BY { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public string STATUS { get; set; }
        public string MSG { get; set; }
        public string BRANCH { get; set; }
        public string FILE_NAME { get; set; }
        public string SENDER { get; set; }
        public string RECEIVED { get; set; }
        public string ACCEPTED_BY { get; set; }
        public Nullable<System.DateTime> ACCEPTED_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETED_DATE { get; set; }
        public string RETURN2BRN_BY { get; set; }
        public Nullable<System.DateTime> RETURN2BRN_DATE { get; set; }
        public string REMARK { get; set; }
        public string ASSIGN2BRN { get; set; }
        public string RETURNED_BY { get; set; }
        public Nullable<System.DateTime> RETURNED_DATE { get; set; }
        public string ASSIGNFROMBRN { get; set; }
        public string LAST_BRN { get; set; }
        public string REJECT_BY { get; set; }
        public Nullable<System.DateTime> REJECT_DATE { get; set; }
        public string PUSH_SWIFT_BY { get; set; }
        public Nullable<System.DateTime> PUSH_SWIFT_DATE { get; set; }
        public string REQUEST_BRN { get; set; }
        public string DEP_CODE { get; set; }
        public string CIF { get; set; }
    }
}
